export const PATHS = {
  HOME: '/',
  SWAP: '/swap',
  LIQUIDITY: '/liquidity',
  CREATE_LIQUIDITY: '/create',
  ADD_LIQUIDITY: '/add',
  ADDA_LIQUIDITY: '/add/:currencyIdA',
  ADDAB_LIQUIDITY: '/add/:currencyIdA/:currencyIdB',
  REMOVE_LIQUIDITY: '/remove/:tokens',
  REMOVEAB_LIQUIDITY: '/remove/:currencyIdA/:currencyIdB',
  MINT: '/mint',
  MINT_TBCC_NFT: '/mint/tbcc-nft-token',
  ANALYTICS: '/analytics',
  BURN: '/burn',
  BURN_RATING: '/burn/rating',
  LOTTERY: '/lottery',
  FARMS: '/farms',
  NFT: '/admin-nft',
  TEAM:'/team'
}
